// <auto-generated />
namespace HealthcardWinForms.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class phase_2__4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(phase_2__4));
        
        string IMigrationMetadata.Id
        {
            get { return "202003250823476_phase_2__4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
